# Generated by Django 4.0.6 on 2022-07-13 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('uid', models.CharField(max_length=500)),
                ('room_name', models.CharField(max_length=150)),
            ],
        ),
    ]
